scene omake_haikei
scene omake_onikakusi
scene omake_haikei
scene omake_tips
scene omake_haikei
scene omake_jump
scene omake_haikei
scene omake_bgm
scene omake_haikei
scene omake_gallery
scene omake_haikei
scene omake_unlock_wata
scene black
scene haikei
$ renpy.full_restart()
