image AgADAgAD_awxGyRLsErqyY1g960qPWnftw8ABAEAAwIAA20AA4FbAgABFgQ # efe/omake_haikei.bmp
image AgADAgAD_qwxGyRLsEpYnyTy2NTmg5Dytw8ABAEAAwIAA20AAwteAgABFgQ # efe/omake_onikakusi.bmp
image AgADAgAD_awxGyRLsErqyY1g960qPWnftw8ABAEAAwIAA20AA4FbAgABFgQ # efe/omake_haikei.bmp
image AgADAgAD_6wxGyRLsErX-9NQ5p1p98rQug8ABAEAAwIAA20AA7H4AAIWBA # efe/omake_tips.bmp
image AgADAgAD_awxGyRLsErqyY1g960qPWnftw8ABAEAAwIAA20AA4FbAgABFgQ # efe/omake_haikei.bmp
image AgADAgADjK0xGxJvsUq0V00EjOxkyFuwhQ8ABAEAAwIAA20AA-e6AwABFgQ # efe/omake_jump.bmp
image AgADAgAD_awxGyRLsErqyY1g960qPWnftw8ABAEAAwIAA20AA4FbAgABFgQ # efe/omake_haikei.bmp
image AgADAgAErTEbJEuwSu4cUKFOKmGrhcq5DwAEAQADAgADbQADwPcAAhYE # efe/omake_bgm.bmp
image AgADAgAD_awxGyRLsErqyY1g960qPWnftw8ABAEAAwIAA20AA4FbAgABFgQ # efe/omake_haikei.bmp
image AgADAgADAa0xGyRLsEpjTCvNg_GT2IDvug8ABAEAAwIAA20AA9_lAAIWBA # efe/omake_gallery.bmp
image AgADAgAD_awxGyRLsErqyY1g960qPWnftw8ABAEAAwIAA20AA4FbAgABFgQ # efe/omake_haikei.bmp
image AgADAgADAq0xGyRLsEr7XlcQzhYjKGfZuQ8ABAEAAwIAA20AA5L7AAIWBA # efe/omake_unlock_wata.bmp
image AgADAgADGawxGxJvqUrkc4W5hsIYJBHptw8ABAEAAwIAA20AAxJYAgABFgQ # efe/black.jpg
image AgADAgADja0xGxJvsUpcJYdDmLXMdw7otw8ABAEAAwIAA20AAw1dAgABFgQ # efe/haikei.jpg
$ renpy.full_restart()
